version: '3.7'
services:
    pages:
        image: streamlit-pages
        restart: unless-stopped
        ports:
        - "8080:80"
        env_file:
        - ./src/config/server.env
        volumes:
          - type: bind
            source: ./mounted_folder
            target: /app/pages

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.60.0/24